# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_auto_20160703_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/public'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/public'),
        ),
    ]
