# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0005_auto_20160708_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/photo'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery/video'),
        ),
    ]
