# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='Photo/logo')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('mail_contact', models.EmailField(blank=True, max_length=70)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('information', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=150)),
                ('twitter', models.CharField(blank=True, max_length=150)),
                ('google', models.CharField(blank=True, max_length=150)),
                ('instgram', models.CharField(blank=True, max_length=150)),
                ('skype', models.CharField(blank=True, max_length=150)),
                ('bannertop', models.ImageField(blank=True, null=True, upload_to='Photo/banner')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('mail_contact', models.EmailField(blank=True, max_length=70)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='Photo/item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('alta_date_created', models.DateField(auto_now_add=True)),
                ('baja_date_created', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('precio_min', models.IntegerField()),
                ('precio_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=15)),
                ('name', models.CharField(max_length=250)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('bannertop', models.ImageField(blank=True, null=True, upload_to='Photo/banner')),
                ('icon', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('texto', models.TextField(blank=True)),
                ('foto_portada', models.ImageField(upload_to='Photo/service')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Service')),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Photo/slider')),
            ],
        ),
        migrations.AddField(
            model_name='pricing',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Service'),
        ),
        migrations.AddField(
            model_name='item',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Service'),
        ),
    ]
