# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('precio_min', models.IntegerField()),
                ('precio_max', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='precio_max',
        ),
        migrations.RemoveField(
            model_name='service',
            name='precio_min',
        ),
        migrations.AddField(
            model_name='pricing',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Service'),
        ),
    ]
