# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20160703_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
