# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_service_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
