# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_inbox_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemportada',
            old_name='foto_preview',
            new_name='photo',
        ),
    ]
