# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20160704_0037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itemPortada',
            new_name='item',
        ),
    ]
