# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_item_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
